Fix NameError in __init__.py
Not sure of the details of either the cause or the fix. On py 3.10, I
get "
```
..../__init__.py", line 31, in <module>
  def _find_changes(original: os.PathLike, patched: os.PathLike) ->
List[Change]:
 NameError: name 'Change' is not defined
```

Fix from #python IRC